### ISSUE TITLE
Fix lists

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-documentation#28]
All lists (bulleted and numbered) are sticking out of their containers

![screen shot 2018-01-16 at 3 38 53 pm](https://user-images.githubusercontent.com/22768918/35011413-ff8cc99c-fad3-11e7-92a7-0eed89d20954.png)

**Comment by shanberg** [comment]
Hanging list bullets and numbers is a common practice in typography (to preserve the line down the left of the text column, keep the layout cleaner, etc) so it was a deliberate choice on my part.

After seeing this issue, I looked at a couple other documentation sites (https://developer.apple.com/documentation/appkit/nsapplication#relationships, https://developer.ibm.com/code/howtos/#!/howto/kafka-authn-authz) and I see it's not common practice.

Given this is documentation designed for people who look at documentation...I'll concede to particular user expectations rather than general conventions here.

**Comment by spmcbride1201** [comment]
The main driver for this was the fact that the bullets and numbers were half on the screen in mobile. For what it's worth, I do generally find the default HTML behavior a bit cleaner to read, but it's totally possible that I've just been thoroughly conditioned to think that way.
