### ISSUE TITLE
Widen content area

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-documentation#31]

**Comment by shanberg** [comment]
The purpose of limiting the width of the paragraph content is to improve the readability.

A good measure (line length) should generally be somewhere between 35-55 em of the body type. Too long and it's easier to lose your place when scanning from the end of one line to the beginning of the next; too short and you spend too much of your reading time moving your eyes down and left, instead of reading actual words.

Embedded content (tables, images, video, etc.) doesn't need to stick to the same width limitations, and there's plenty of room to fudge things and break out of the boundaries, but I do want to stick to a good measure for the bulk of the content that's made for reading.

**Comment by shanberg** [comment]
OBE
